// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLOX6x0ThAcBoRo9DF3g3dUzYljhQvU4',
    appId: '1:641894575381:web:83d30d152a07b17d980d1c',
    messagingSenderId: '641894575381',
    projectId: 'grocery-app-ea4b9',
    authDomain: 'grocery-app-ea4b9.firebaseapp.com',
    storageBucket: 'grocery-app-ea4b9.appspot.com',
    measurementId: 'G-LZHSVR1QM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wZ9hKmaZY60O7wu9tS7riC05ea9UzEE',
    appId: '1:641894575381:android:c840aa0c9494ad43980d1c',
    messagingSenderId: '641894575381',
    projectId: 'grocery-app-ea4b9',
    storageBucket: 'grocery-app-ea4b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbcolVYrS9h-99XHy5E2Dt9JTH6Q1WPwQ',
    appId: '1:641894575381:ios:b68cd2a091c8c4ff980d1c',
    messagingSenderId: '641894575381',
    projectId: 'grocery-app-ea4b9',
    storageBucket: 'grocery-app-ea4b9.appspot.com',
    androidClientId: '641894575381-achnk8o4le7qa6m0ea9ce47on004adfk.apps.googleusercontent.com',
    iosClientId: '641894575381-3viqj5b86i0ct6e7l6hfves4rg7v1c0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbcolVYrS9h-99XHy5E2Dt9JTH6Q1WPwQ',
    appId: '1:641894575381:ios:b68cd2a091c8c4ff980d1c',
    messagingSenderId: '641894575381',
    projectId: 'grocery-app-ea4b9',
    storageBucket: 'grocery-app-ea4b9.appspot.com',
    androidClientId: '641894575381-achnk8o4le7qa6m0ea9ce47on004adfk.apps.googleusercontent.com',
    iosClientId: '641894575381-3viqj5b86i0ct6e7l6hfves4rg7v1c0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
